// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAajkEaZwpNfDwnzi36ncFKQQg6y-EqChk',
    appId: '1:100724612618:web:362cdac8ac17ae0a8189f3',
    messagingSenderId: '100724612618',
    projectId: 'charlie-6d4ab',
    authDomain: 'charlie-6d4ab.firebaseapp.com',
    storageBucket: 'charlie-6d4ab.appspot.com',
    measurementId: 'G-Q8LLY7FL4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4f_7RN_T4cz21frSh6QpDijZUZj6OcJ8',
    appId: '1:100724612618:android:d32e9cf28e778a6f8189f3',
    messagingSenderId: '100724612618',
    projectId: 'charlie-6d4ab',
    storageBucket: 'charlie-6d4ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWjvtl7opThDB11JCvsEBhXotEb-0ZNDQ',
    appId: '1:100724612618:ios:377022ae0e69ab158189f3',
    messagingSenderId: '100724612618',
    projectId: 'charlie-6d4ab',
    storageBucket: 'charlie-6d4ab.appspot.com',
    iosClientId: '100724612618-d17pbon2pv6bm9vodcsei2ehbp5bn2vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
